# Generated by Django 3.2.3 on 2021-05-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('length', models.FloatField()),
                ('elevation_gain', models.IntegerField()),
                ('route_type', models.CharField(choices=[('LP', 'Loop'), ('OB', 'Out & back'), ('PP', 'Point to point')], max_length=2)),
            ],
        ),
    ]
