# Generated by Django 3.2.3 on 2021-05-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Moderate'), ('H', 'Hard')], default='E', max_length=1),
            preserve_default=False,
        ),
    ]
