# Generated by Django 3.2.3 on 2021-05-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='completed', to='main_app.Hike'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='main_app.Hike'),
        ),
    ]
