# Generated by Django 3.2.3 on 2021-05-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210525_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='average_rating',
            field=models.IntegerField(null=True),
        ),
    ]
