# Generated by Django 3.2.3 on 2021-05-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_hike_average_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('Hi', 'Hiking'), ('MB', 'Mountain Biking'), ('TR', 'Trail Running'), ('Ba', 'Backpacking'), ('Wa', 'Walking'), ('RB', 'Road Biking'), ('ORD', 'Off Road Driving'), ('Ca', 'Camping'), ('BW', 'Bird Watching'), ('HR', 'Horseback Riding'), ('NT', 'Nature Trips'), ('Fi', 'Fishing'), ('Sn', 'Snowshoeing'), ('SD', 'Scenic Driving'), ('RC', 'Rock Climbing'), ('PS', 'Paddle Sports'), ('XC', 'Cross Country Skiing'), ('Sk', 'Skiing'), ('BT', 'Bike Touring'), ('VF', 'Via Ferrata')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='hike',
            name='activities',
            field=models.ManyToManyField(to='main_app.Activity'),
        ),
    ]
