# Generated by Django 3.2.3 on 2021-05-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210528_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hike',
            name='activities',
        ),
        migrations.AddField(
            model_name='activity',
            name='hike',
            field=models.ManyToManyField(to='main_app.Hike'),
        ),
    ]
